Fix #668
denoland/vscode_deno pull request #745
Opened 2022-11-04 17:40 UTC by asyncmax

Path separators on Windows caused an incorrect behavior in `#fileNameDenoEnabled` that resulted in a non-functioning `deno.enablePaths` setting on Windows. This fixes #668.

2022-11-04 17:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/vscode_deno?pullRequest=745) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/vscode_deno?pullRequest=745) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/vscode_deno?pullRequest=745) it.</sub>

2022-11-11 02:32 UTC, dsherret commented on typescript-deno-plugin/src/index.ts
> +      fileName = fileName.replace(/\//g, "\\");
I think this might break the indexing into `settings?.documents?.[fileName]` below?

2022-11-11 02:36 UTC, dsherret requested changes
Good catch and thanks for the PR! This occurs because typescript normalizes all slashes as `/`.

See my comment in the PR though as I'm not sure about the fix. It might be ok.

2022-11-11 02:50 UTC, dsherret commented on typescript-deno-plugin/src/index.ts
> +      fileName = fileName.replace(/\//g, "\\");
It fixes it. This is an fsPath.

2022-11-11 02:51 UTC, merged

2022-11-26 19:13 UTC, webdev3301 commented
Hello. I have just tested v3.14.1 on Windows and the language server doesn't start.
I reversed back to v3.14.0 and everything worked fine again.

2023-05-18 23:58 UTC, cpakken commented
> Hello. I have just tested v3.14.1 on Windows and the language server doesn't start. I reversed back to v3.14.0 and everything worked fine again.

Same, enablePaths doesn't work for me either in Windows 10 (Deno v1.33.4) How do you see Deno's language server version?

2023-05-19 00:19 UTC, cpakken commented
> > Hello. I have just tested v3.14.1 on Windows and the language server doesn't start. I reversed back to v3.14.0 and everything worked fine again.
> 
> Same, enablePaths doesn't work for me either in Windows 10 (Deno v1.33.4) How do you see Deno's language server version?

deno.enablePaths seems to activate when I use the full absolute paths on windows. But the typescript server isn't disabled.
![image](https://github.com/denoland/vscode_deno/assets/61718569/3841a75c-d5b6-4579-bccf-5898f4c40a2b)

Here is using relative paths. Deno is not enabled
![image](https://github.com/denoland/vscode_deno/assets/61718569/91457af3-831c-4475-b5fc-328aa8686e87)
Works without deno.enablePaths
![image](https://github.com/denoland/vscode_deno/assets/61718569/f7c1d3c4-a511-43c7-b109-84d15949c44a)

But other files in my workspace breaks